<?php

namespace JeyKeu\PHPLookup;

use JeyKeu\PHPLookup\PHPLookup;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-14 at 11:23:10.
 */
class PHPLookupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PHPLookup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPLookup();
    }

    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

//    /**
//     * @covers JeyKeu\PHPLookup\PHPLookup::vLookup
//     * @todo   Implement testVLookup().
//     * 
//     */
//    public function testVLookup() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}
